### ISSUE TITLE
QuestionTypeSeeder error

### ISSUE THREAD

**Issue by alex1897** [harishdurga/laravel-quiz#16]
Hi,

I found that the migration for the QuestionTypeSeeder throws an error.
<img width="803" alt="Bildschirmfoto 2022-07-22 um 14 46 32" src="https://user-images.githubusercontent.com/6780121/180446835-0eacceb0-d5f5-4bb0-b0ad-0423ff95a788.png">

From my knowledge the create() supports only one record. The insert() supports many records but does not automatically update the timestamps. One option would be:

```
$questionTypes = [
            [
                'name' => 'multiple_choice_single_answer',
            ],
            [
                'name' => 'multiple_choice_multiple_answer',
            ],
            [
                'name' => 'fill_the_blank',
            ]
        ];

        foreach ($questionTypes as $questionType) {
            QuestionType::create($questionType);
        };
```

All the best
Alex

**Comment by harishdurga** [comment]
Hey @alex1897. Thank you for reporting this. Can you provide what version of Laravel you are using?

**Comment by alex1897** [comment]
Hi @harishdurga. Yes sure I have the newest version Laravel 9.21.5.

**Comment by harishdurga** [comment]
Please feel free to reopen the issue if you are still having the issue.

**Comment by alex1897** [comment]
I tested this and the migration throws an error now:
<img width="912" alt="image" src="https://user-images.githubusercontent.com/6780121/182197654-e207c6dc-3467-411a-a973-4600ff0afee5.png">

I guess the reason for that is that you've changed in #17:
\- namespace Database\Seeders;
\+ namespace Harishdurga\LaravelQuiz\Database\Seeders;

**Comment by harishdurga** [comment]
I was facing some issues while writing a test case for the seeder and I changed the namespace. Can you try running the following command?
```bash
php artisan db:seed --class=\\Harishdurga\\LaravelQuiz\\Database\\Seeders\\QuestionTypeSeeder
```

**Comment by alex1897** [comment]
That indeed works. However if you follow the README  and publish the Vendor Files:
`php artisan vendor:publish --provider="Harishdurga\LaravelQuiz\LaravelQuizServiceProvider"`

And then use as described:
`php artisan db:seed --class=QuestionTypeSeeder`

the error comes up.

**Comment by harishdurga** [comment]
I will update the seeder command in the README accordingly then.
