### ISSUE TITLE
Topic slug unique with soft delete

### ISSUE THREAD

**Issue by alex1897** [harishdurga/laravel-quiz#18]
I think the "string('slug')->unique()" for the model Topic is misleading in combination wit soft delete. If a topic "Test" is created and deleted it can never be added anymore. In my opinion the id should be the unique key and the validation should handle it.

Create Validation:
`'slug' => 'string|required|unique:topics,slug,NULL,id,deleted_at,NULL'`

Update Validation:
`'slug' => 'string|required|unique:topics,slug,' . $topic->id . ',id,deleted_at,NULL',`

What do you think?

**Comment by harishdurga** [comment]
Hey @alex1897 , yeah your suggestions make sense. I will work on this. Thank you.
