### ISSUE TITLE
Update to Laravel 9

### ISSUE THREAD

**Issue by Obi-Wana** [harishdurga/laravel-quiz#2]
Laravel 9 will be released in mid. February. 
An update would be great to work with Laravel 9 applications.

There is laravel/framework 9.x-dev already available.

https://laravelshift.com/ May help.

**Comment by harishdurga** [comment]
Some of the dependencies are not yet updated. I have to wait for those to be updated.

**Comment by harishdurga** [comment]
Updated to support Laravel 9.
