### ISSUE TITLE
ERM model

### ISSUE THREAD

**Issue by alex1897** [harishdurga/laravel-quiz#22]
I checked the ERM and I found some differences: 
![173225090-8dc96205-1a08-4ed2-8954-1a53bccc7359](https://user-images.githubusercontent.com/6780121/182210931-ee7d7d55-eeff-41fb-8dcc-5184a859daaa.png)

Completely missing seems to be the "QuestionTopic" since I did't find how to connect a "Topic" and a "Question". There is also no migration existing for that. What is the need of "Topic"?

Another question I have is the table "topicables" which is not part or the ERM and seems not be used.

**Comment by harishdurga** [comment]
@alex1897 Yeah it seems I have to update the diagram and README covering the things you have mentioned. `Topic` is useful to categorize the content. Consider a topic as `Computer Science` . So If I attach this topic to some of my questions, a filter can be added to the application where a user can see questions for the `Computer Science` topic. The same goes for the Quizzes as well. So currently you can attach topics to questions and quizzes.
```php
$topic1 = Topic::factory()->create(['topic' => 'Test Topic One']);
        $topic2 = Topic::factory()->create(['topic' => 'Test Topic Two']);
        $question = Question::factory()->create();
        $question->topics()->attach($topic1);
        $question->topics()->attach($topic2);
```
```php
$quiz = Quiz::factory()->make()->create([
            'name' => 'Sample Quiz',
            'slug' => 'sample-quiz',
        ]);
        $topic_one = Topic::factory()->make()->create([
            'name' => 'Topic One',
            'slug' => 'topic-one',
        ]);
        $topic_two = Topic::factory()->make()->create([
            'name' => 'Topic Two',
            'slug' => 'topic-two',
        ]);
        $quiz->topics()->attach([$topic_one->id, $topic_two->id]);
```

**Comment by alex1897** [comment]
I forgot that a question is not directly linked to quiz. A categorization with topics makes defiantly sense, especially when building quizzes afterwards, then you could filter by a specific topic. Also, for your planned "Generate Random Quizzes" it is helpful to make use only a specific topic.

However, this is realized with topicables instead of question_topics as in the ERM model, right?

**Comment by harishdurga** [comment]
Yes, that's correct. The diagram needs to be updated. As you already know there is no `question_topics` table but a `topicables` table can host the links of topics to questions, and quizzes. If we can create a `topicable` trait, then this can be extended to other types of models as well.
