### ISSUE TITLE
Undefined array key 0

### ISSUE THREAD

**Issue by alex1897** [harishdurga/laravel-quiz#34]
Hi @harishdurga,

I checked your newest release it works fine with the first attempt. In the second I receive the following error: "Undefined array key 0".

<img width="1470" alt="Bildschirm­foto 2023-02-10 um 11 14 44" src="https://user-images.githubusercontent.com/6780121/218066095-f986e430-e124-407d-92da-b3d09208de28.png">

All the best
Alex

**Comment by harishdurga** [comment]
Hey @alex1897 Can you please try `34-undefined-array-key-0` branch for this issue and let me if you are still facing any issues?

**Comment by alex1897** [comment]
Hi @harishdurga that has fixed it. Thank! :)
