### ISSUE TITLE
laravel 10 illuminate/support error

### ISSUE THREAD

**Issue by ghost** [harishdurga/laravel-quiz#36]
i dont know much but when i try to install i get this below error

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires harishdurga/laravel-quiz ^1.2 -> satisfiable by harishdurga/laravel-quiz[v1.2.0, v1.2.1].
    - harishdurga/laravel-quiz[v1.2.0, ..., v1.2.1] require illuminate/support ^9.0 -> found illuminate/support[v9.0.0, ..., v9.52.5] but these were not loaded, likely because it conflicts with another require.

You can also try re-running composer require with an explicit version constraint, e.g. "composer require harishdurga/laravel-quiz:*" to figure out if any version is installable, or "composer require harishdurga/laravel-quiz:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by harishdurga** [comment]
PR: #40 
Try reinstalling the package. Feel free to re-open the issue if you are still facing the issue.
