### ISSUE TITLE
Topicable namespace 

### ISSUE THREAD

**Issue by AcriCAA** [harishdurga/laravel-quiz#38]
The namespace for the Topicable model is currently 'namespace App\Models;` but should be `namespace Harishdurga\LaravelQuiz\Models;` like the others in the package so it could be accessed elsewhere. 

For example, you cannot run `Topicable::truncate();`

**Comment by AcriCAA** [comment]
@harishdurga happy to create a pull request for a fix for this if you want but figured it would be easiest for you if you just made the modification with whatever else you are doing in your next release. If not, let me know and I'll take care of it.

**Comment by harishdurga** [comment]
I'm sorry for not getting back to you sooner. I will work on this issue as soon as possible and resolve it.
