### ISSUE TITLE
Wrong Class Diagram

### ISSUE THREAD

**Issue by ades4827** [harishdurga/laravel-quiz#4]
There is a small error in the class diagram as shown in the image
![126498504-6b0f3956-67c7-47f7-88b1-653b33f9dd77](https://user-images.githubusercontent.com/27701869/171991787-fa025615-06ba-4218-9daa-fc13f87b259d.jpg)

**Comment by harishdurga** [comment]
Thank you for pointing this out. I will update this along with some other changes in the testing phase.

**Comment by harishdurga** [comment]
Class diagram corrected.
