### ISSUE TITLE
How topicables relate to Questions

### ISSUE THREAD

**Issue by calebnanigah** [harishdurga/laravel-quiz#44]
When topics are attached to a question, the topic_ids are created in the topicables table.

However, I do not see any relation between the topics and the questions.

How is topicables table related to the questions table?

**Comment by harishdurga** [comment]
Basically we attach topics to questions like tags or categories so that it is easy to fetch questions of a specific category.

**Comment by calebnanigah** [comment]
@harishdurga , thank you for your response. 

After creating quizzes and questions with attached topics, I observed how topicables work: 
 when a quiz is created, topicable_id is the ID of the quiz, when a question is created topicable_id, is the ID/IDs of the questions (attached topics in both cases)
