### ISSUE TITLE
Json default value

### ISSUE THREAD

**Issue by ades4827** [harishdurga/laravel-quiz#8]
I'm having a problem migrating the database. Unfortunately, using the basic configurations of MySql there is an error. Can you remove the default value of the json negative_marking_settings field?

Error:
SQLSTATE[42000]: Syntax error or access violation: 1101 BLOB, TEXT, GEOMETRY or JSON column 'negative_marking_settings' can't have a default value 

https://stackoverflow.com/questions/38433603/mysql2error-blob-text-geometry-or-json-column-body-cant-have-a-default-v

**Comment by harishdurga** [comment]
What is your MySql version? 5.7 or 8?

**Comment by ades4827** [comment]
I tried both the latest version of the 5 and the latest version of the 8

**Comment by harishdurga** [comment]
Okay. I am on the issue. Can you try this branch and let me know if this works? `hotfix/8` then I will merge the fix.

**Comment by harishdurga** [comment]
You won't be facing the issue now. Please check and re-open the issue if you are still having problems.
